Update pselc

diff --git a/pselc b/pselc
--- a/pselc
+++ b/pselc
@@ -61,6 +61,13 @@ then
 	then
 		READER="okular"
 	fi
+	
+	which zathura &>/dev/null
+	if [ $? -eq 0 ]
+	then
+		READER="zathura"
+	fi
+
 fi
 
 # Exit if no PDF reader found
@@ -106,7 +113,7 @@ then
 fi
 
 # Use BASH's inbuilt select utility to prompt for user input
-echo ""
+echo "Type q to quit"
 select choice in "${array[@]}"
 do
 	for (( i=0 ; i<$array_size ; i++ ))
@@ -116,8 +123,10 @@ do
 			$READER "$choice" &>/dev/null &
 			clear
 			exit
+		else
+			exit
 		fi
 	done
 	echo ""
-	echo "Invalid choice"
+	echo "Invalid choice" 
 done
